larning_users/larning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from my_app import views

urlpatterns = [
    path("",views.index, name="index"),
    path("admin/", admin.site.urls),
    path("my_app/",include("my_app.urls")),
    path("logout/",views.user_logout,name="logout"),
    path("special/",views.special, name="special")
]

larning_users/my_app/urls.py
from django.urls import path,include
from my_app import views

app_name="my_app"

urlpatterns=[
    path('register/',views.register,name='register'),
    path("user_login/",views.user_login,name="user_login"),
    
]

larning_users/my_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    #create a relationship (don't inherit from User!)
    user=models.OneToOneField(User,on_delete=models.PROTECT)

    #Add any additional attributes you want
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.usernam
    

larning_users/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

larning_users/my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm,UserProfileInfoForm
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

def index(request):
    return render(request,'my_app/index.html')

def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))



def register(request):
    registered=False

    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)

            profile.user=user
        
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    
    return render(request,'my_app/registration.html',
                    {'user_form':user_form,
                    'profile_form':profile_form,
                   'registered':registered})

def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")

        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("index"))
        
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,"my_app/login.html",{})    
        

larning_users/templates/my_app/base.html
<html>
    <head>
        <meta charset="utf-8">
        <title>FORMS</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{%url 'index'%}">HOME</a></li>
                    <li><a class="navbar_link" href="{%url 'admin:index'%}">Admin</a></li>
                    <li><a class="navbar_link" href="{%url 'my_app:register'%}">REGISTER</a></li>
                
                    {%if user.is_authenticated %}
                        <li><a class="navbar-link" href="{%url "logout"%}">Logout</a>
                    {%else%}
                        <li><a class="navbar-link" href="{%url "my_app:user_login"%}">Login</a>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    </body>
</html>

larning_users/templates/my_app/index.html
<!DOCTYPE html>
{%extends "my_app/base.html"%}
    {% block body_block%}
    <div class="jumbodron">
        <h1> Hello! This is home Page </h1>
    </div>
    {% endblock%}

larning_users/templates/my_app/login.html
{%extends "my_app/base.html"%}
{% block body_block%}
<head>
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    <div class="jumbodron">
</head>
<style>
    #boddy {
      display: -ms-flexbox;
      display: -webkit-box;
      display: flex;
      -ms-flex-align: center;
      -ms-flex-pack: center;
      -webkit-box-align: center;
      align-items: center;
      -webkit-box-pack: center;
      justify-content: center;
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #f5f5f5;
    }

    .abab{

        text-align: center;
    }

    .form-signin {
      width: 100%;
      max-width: 330px;
      padding: 15px;
      margin: 0 auto;
    }
    .form-signin .checkbox {
      font-weight: 400;
    }
    .form-signin .form-control {
      position: relative;
      box-sizing: border-box;
      height: auto;
      padding: 10px;
      font-size: 16px;
    }
    .form-signin .form-control:focus {
      z-index: 2;
    }
    .form-signin input[type="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
</style>
    <div id="boddy">
        <form action=""{%url 'my_app:user_login'%}" method="post" class="form-signin">
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal abab">Please Sign in</h1>
            <label for="username" class="sr-only"> Username: </label>
            <input type="text" name="username" id="username" placeholder="Enter Username" class="form-control">
            <br>
            <label for="password" class="sr-only">Password: </label>
            <input type="password" id="password" name="password" class="form-control" placeholder="Password">
            <br>
            <button type="submit" name="" value="Login" class="btn btn-lg btn-primary btn-block">Sign in</button>
        </form>
    </div>
    
{%endblock%}


<!-- {%extends "my_app/base.html"%}
{% block body_block%}
    <div class="jumbodron">
        <h1> Please Login </h1>
        <form action=""{%url 'my_app:user_login'%}" method="post">
            {% csrf_token %}
            <label for="username">Username: </label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password: </label>
            <input type="password" name="password" >

            <input type="submit" name="" value="Login">
        </form>
    </div>
{%endblock%} -->

larning_users/templates/my_app/registration.html
{%extends "my_app/base.html"%}
{% block body_block%}
    {%load static%}
        <div class="jumbodron">
            {%if registered%}
                <h1>Thank you for registering</h1>
            {%else%}
                <h3>Fill out the form: </h3>

                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {{user_form.as_p}}
                    {{profile_form.as_p}}
                    <input type="submit" name"" value="Register">
           
     </form>
            {%endif%}
        </div>
    {%endblock%}